# Generates a C++ translation unit defining a byte array from a binary file, so the
# genotype-quality model file (IN_FILE, set to GQ_MODEL_FILE by CMakeLists.txt) is compiled
# into the ExpansionHunter binary. Invoked by an add_custom_command in CMakeLists.txt.
#
# Inputs (passed via -D):
#   IN_FILE  - the binary file to embed
#   OUT_FILE - the .cpp file to generate
#
# An empty IN_FILE (the checked-in placeholder, before the trained model exists)
# produces a zero-length array so loadEmbeddedGenotypeQualityModel() returns null.

file(READ "${IN_FILE}" hex HEX)
string(LENGTH "${hex}" hexLength)
math(EXPR numBytes "${hexLength} / 2")

if(numBytes EQUAL 0)
    set(bytes "0") # placeholder element; never read because the length is 0
else()
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
endif()

file(WRITE "${OUT_FILE}"
"// Generated by cmake/EmbedModel.cmake from ${IN_FILE}. Do not edit.\n"
"#include <cstddef>\n"
"namespace ehunter\n"
"{\n"
"namespace gq\n"
"{\n"
"extern const unsigned char kEmbeddedModelGz[] = { ${bytes} };\n"
"extern const std::size_t kEmbeddedModelGzLen = ${numBytes};\n"
"} // namespace gq\n"
"} // namespace ehunter\n")
